name: Python unittest
on: [pull_request]

jobs:
  unittest:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # pytest をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      # pytest を使ってテスト実施、結果を xml ファイルに出力
      # unittestのスクリプトは pytest と互換性があり、そのまま実行できる
      - name: Run tests with pytest
        run: |
          pytest test.py --junitxml=test-results.xml
