name: Python unittest
on: [pull_request]

# 必要な権限を指定
# https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
permissions:
  checks: write
  pull-requests: write

jobs:
  unittest:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # pytest をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      # pytest を使ってテスト実施、結果を xml ファイルに出力
      # unittestのスクリプトは pytest と互換性があり、そのまま実行できる
      - name: Run tests with pytest
        run: |
          pytest test.py --junitxml=test-results.xml
        continue-on-error: true
      # テスト結果のxmlファイルを可視化する
      # https://github.com/EnricoMi/publish-unit-test-result-action
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: test-results.xml
