name: Python unittest
on: [pull_request]

jobs:
  unittest:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # pytest をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      # pytest を使ってテスト実施、結果を xml ファイルに出力
      # unittestのスクリプトは pytest と互換性があり、そのまま実行できる
      - name: Run tests with pytest
        run: |
          pytest test.py --junitxml=test-results.xml
      # 結果をアップロードする
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results
          path: test-results.xml
      # テスト結果のxmlファイルを可視化する
      # https://github.com/EnricoMi/publish-unit-test-result-action
      - name: Download Unit Test Results
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: artifacts\*.xml
